export const proyects = [
  {
    id: 1,
    title: 'PROYECTO DE GRADO',
    link: 'https://colegio.vercel.app/',
    text: 'Proyecto de grado de secundaria de una alternativa de solución para mejorar la calidad evaluativa online del docente de 5to A, En el Colegio María Santísima ',
    logos: ['/src/assets/logos/react.png', '/src/assets/logos/firebase.png', '/src/assets/logos/chakra-ui.png'],
    url: '/src/assets/proyects/colegio.png',
    alt: 'colegio'
  },
  {
    id: 2,
    title: 'ANIMALIA',
    link: 'https://proyect-psi.vercel.app/',
    text: 'Sitio web para prensentar las mejores imagenes con su mejor calidad',
    logos: ['/src/assets/logos/next.png', '/src/assets/logos/chakra-ui.png'],
    url: '/src/assets/proyects/animale.png',
    alt: 'animales',
  },
  {
    id: 3,
    title: 'CARTAS MARIO BROS',
    link: 'https://rohyllerp.github.io/cartas/',
    text: 'Sitio web para juego de cartas con tiempo y mejor tiempo incluido',
    logos: ['/src/assets/logos/javascript.png', '/src/assets/logos/bootstrap.png', '/src/assets/logos/css.png', '/src/assets/logos/html-5.png'],
    url: '/src/assets/proyects/cartas.png',
    alt: 'cartas',
  },
  {
    id: 4,
    title: 'Almacen',
    link: 'http://gestor.myartsonline.com/',
    text: 'Mini sitio web con LOGIN, y vista para productos',
    logos: ['/src/assets/logos/php.png', '/src/assets/logos/mysql.png',
      '/src/assets/logos/javascript.png', '/src/assets/logos/bootstrap.png',
      '/src/assets/logos/css.png', '/src/assets/logos/html-5.png'],
    url: '/src/assets/proyects/almacen.png',
    alt: 'Almacen',
  },
  {
    id: 5,
    title: 'NOTAS',
    link: 'https://rohyllerp.github.io/notas/',
    text: 'Sitio web de un ejemplo de "to-do list" donde podemos crear categorias y en esas categorias crear tareas, editar tareas, eliminar tareas y más. Todas estas se guardarán a pesar que cierres la ventana.',
    logos: ['/src/assets/logos/html-5.png', '/src/assets/logos/bootstrap.png', '/src/assets/logos/jquery.png'],
    url: '/src/assets/proyects/notas.png',
    alt: 'notas',
  },
  {
    id: 6,
    title: 'CALCULADORA',
    link: 'https://rohyllerp.github.io/calculadora/',
    text: 'Sitio web responsive de ejemplo de una calculadora funcional, tiene además cambio de color en modo oscuro y modo claro.',
    logos: ['/src/assets/logos/html-5.png', '/src/assets/logos/css.png', '/src/assets/logos/javascript.png'],
    url: '/src/assets/proyects/calculadora.png',
    alt: 'calculadora',
  },
  {
    id: 7,
    title: 'Calculadora de edad',
    link: 'https://rohyllerp.github.io/age-calculator/',
    text: 'Calculadora de edad referente a la fecha de nacimiento y a la fecha actual dando años que han transcurrido, meses y dias',
    logos: ['/src/assets/logos/html-5.png', '/src/assets/logos/css.png', '/src/assets/logos/javascript.png'],
    url: '/src/assets/proyects/age-calculator.png',
    alt: 'age calculator',
  },
  {
    id: 8,
    title: 'Tic tac toe',
    link: 'https://tic-tac-toe-rohyllerp.vercel.app/',
    text: 'EL juego famoso llamado Tic-tac-toe "la vieja" en algunos países',
    logos: ['/src/assets/logos/html-5.png', '/src/assets/logos/css.png', '/src/assets/logos/vue.png'],
    url: '/src/assets/proyects/tic-tac-toe.png',
    alt: 'tic-tac-toe',
  },
  {
    id: 9,
    title: 'Facebook view',
    link: 'https://rohyllerp.github.io/face-view/',
    text: 'Sitio web de una pagina de facebook probando e utilizando el framework de boostrap con sus componentes.',
    logos: ['/src/assets/logos/html-5.png', '/src/assets/logos/bootstrap.png'],
    url: '/src/assets/proyects/facebook-view.png',
    alt: 'face-view',
  },
  {
    id: 10,
    title: 'Consumiendo api de CADIF1',
    link: 'https://rohyllerp.github.io/api-CADIF1/',
    text: 'Página web que consume una api de CADIF1 con FETCH.',
    logos: ['/src/assets/logos/html-5.png', '/src/assets/logos/css.png', '/src/assets/logos/jquery.png'],
    url: '/src/assets/proyects/api-cadif1.png',
    alt: 'api-cadif1',
  }
];